var Beer = require(__dirname + '/../models/beer.js');

newBeers = [
new Beer({name: 'Abt 12', type: 'Quadrupel', brewery: 'St. Bernardus Brouweij', abv: 10, summary: 'The St. Bernardus Abt 12 is the pride of our stable, the nec plus ultra of our brewery. Abbey ale brewed in the classic ’Quadrupel’ style of Belgium’s best Abbey Ales. Dark with a full, ivory-colored head. It has a fruity aroma, full of complex flavours and excels because of its long bittersweet finish with a hoppy bite. Worldwide seen as one of the best beers in the world. It’s a very balanced beer, with a full-bodied taste and a perfect equilibrium between malty, bitter, and sweet. One of the original recipes from the days of license-brewing for the Trappist monks of Westvleteren.', picture: 'http://res.cloudinary.com/ratebeer/image/upload/w_250,c_limit/beer_2530.jpg'}),
new Beer({name: 'Pumking', type: 'Pumkin Ale', brewery: 'Southern Tier', abv: 8.6, summary: 'Pumking is an ode to Púca, a creature of Celtic folklore, who is both feared and respected by those who believe in it. Púca is said to waylay travelers throughout the night, tossing them on its back, and providing them the ride of their lives, from which they return forever changed. Brewed in the spirit of All Hallows Eve, a time of the year when spirits can make contact with the physical world and when magic is most potent. Pour Pumking into a goblet and allow it’s alluring spirit to overflow. As spicy aromas present themselves, let it’s deep copper color entrance you as your journey into this mystical brew has just begun. As the first drops touch your tongue a magical spell will bewitch your taste buds making it difficult to escape the Pumking.', picture: 'http://res.cloudinary.com/ratebeer/image/upload/w_250,c_limit/beer_77640.jpg'}),
new Beer({name: 'Rare Vos', type: 'Belgian Ale', brewery: 'Ommegang', abv: 6.5, summary: 'Rare Vos is flemmish for "Sly Fox," and the name of one of Brussels’ great cafes. It has a sweetly fruity malt character and yeasty spiciness. A fine dose of yeast permits the beer to mature and mellow in the bottle.', picture: 'http://res.cloudinary.com/ratebeer/image/upload/w_250,c_limit/beer_8838.jpg'}),
new Beer({name: 'Interurban IPA', type: 'India Pale Ale', brewery: 'Fremont Brewing Company', abv: 6.2, summary: 'Named after Fremont’s most famous outdoor sculpture, Waiting for the Interurban, Interurban India Pale Ale offers the adventurous beer lover a warm embrace of organic Gambrinus roasted pale malt swirled with a hand-selected blend of flavor malts and filled with the rich spice of Chinook, Centennial and Cascade hops. Interurban India Pale is a session beer, eminently drinkable throughout the year.', picture: 'http://res.cloudinary.com/ratebeer/image/upload/w_250,c_limit/beer_104576.jpg'})
];

newBeers.map(function(beer) {
  beer.save(function(err, data) {
    if(err) throw err;
  });
});
